### ISSUE TITLE
Is this a user role issue?

### ISSUE THREAD

**Issue by BurlesonBrad** [anspress/anspress#503]
PHP Fatal error: Uncaught Error: Call to a member function has_cap() on boolean in /woocamp/wp-content/plugins/anspress/includes/class/roles-cap.php:1515
Stack trace:
#0 /woocamp/wp-content/plugins/anspress/includes/comments.php(341): ap_user_can_read_comments(Object(WP_Post))
#1 /woocamp/wp-content/plugins/anspress/includes/comments.php(417): ap_the_comments(Object(WP_Post), Array, true)
#2 /woocamp/wp-content/plugins/anspress/templates/single-question.php(113): ap_post_comments()
#3 /woocamp/wp-content/plugins/anspress/includes/common-pages.php(131): include('/woocamp/wp-con...')
#4 /woocamp/wp-content/plugins/anspress/includes/class-theme.php(58): AnsPress_Common_Pages::question_page()
#5 /wordpress/core/4.9.8/wp-includes/class-wp-hook.php(286): AnsPress_Theme::template_include_theme_compat('/woocamp/wp-con...')
#6 /wordpress/core/4.9.8/wp-includes/plugin.php(203): WP_Hook->apply_filters('/woocamp/wp-con...', Array)
#7 /woocamp/wp-content/plugins/anspress/includes/class-theme.php(42): app

Hey @rahularyan , here's the stack trace for the error I'm getting 
And, here's the screenshot of the settings:
![image](https://user-images.githubusercontent.com/6208757/46303052-6e292780-c570-11e8-875e-8ff5cea6bccb.png)
And here's a few links:
https://woocamp.com/questions/categories/plugin-suggestions/ 
A ```user_role``` of _"Anyone"_ should be able to read & see the questions. However....
https://woocamp.com/woocommerce-help/i-am-looking-for-suggestions-for-multi-currency-plugins-for-woocommerce-and-geo-ip-detection/
....only a ```user_role``` of _"Student"_  should be able to see the answers.

Have I missed something?

**Comment by rahularyan** [comment]
Hi Brad, Let me check this.

**Comment by BurlesonBrad** [comment]
❗️ attn: @rahularyan 👉 Thanks to @jtedrow87 👍, here's the fix:

https://gist.github.com/BurlesonBrad/1503f55b1c999621849e930ce862c73e

**Comment by rahularyan** [comment]
Thanks for shearing it.
I cannot add try catch in function, I will replace it with a WP_Error.

**Comment by jtedrow87** [comment]
How come you cannot add a try catch?
Should be able to just do a return of a **WP_Error** object in the catch

**Comment by rahularyan** [comment]
Yeh right. will merge it.
